export const dashboard = <i className="fa-solid fa-house-chimney"></i>
export const transactions = <i className="fa-solid fa-credit-card"></i>
export const categories = <i className="fa-solid fa-layer-group"></i>
export const accounts = <i className="fa-solid fa-wallet"></i>
export const settings = <i className ="fa-solid fa-gear"></i>
export const logout = <i className="fa-solid fa-right-from-bracket"></i>
export const trend = <i className="fa-solid fa-money-bill-trend-up"></i>
export const expenses = <i className="fa-solid fa-cart-shopping"></i>
export const money = <i className="fa-solid fa-money-bills"></i>
export const freelance = <i className="fa-solid fa-globe"></i>
export const stocks = <i className="fa-solid fa-arrow-trend-up"></i>
export const bitcoin = <i className="fa-brands fa-bitcoin"></i>
export const piggy = <i className="fa-solid fa-piggy-bank"></i>
export const card = <i className="fa-brands fa-cc-mastercard"></i>
export const users = <i className="fa-solid fa-users"></i>
export const dollar = <i className="fa-solid fa-hryvnia-sign"></i>
export const calender = <i className="fa-solid fa-calendar-days"></i>
export const comment = <i className="fa-solid fa-comments"></i>
export const plus = <i className="fa-regular fa-square-plus"></i>
export const trash = <i className="fa-solid fa-trash-can"></i>
export const signout = <i className="fa-solid fa-door-open"></i>
export const takeaway = <i className="fa-solid fa-utensils"></i>
export const clothing = <i className="fa-solid fa-shirt"></i>
export const book = <i className="fa-solid fa-book-open"></i>
export const food = <i className="fa-solid fa-bowl-food"></i>
export const medical = <i className="fa-solid fa-briefcase-medical"></i>
export const tv = <i className="fa-solid fa-tv"></i>
export const circle = <i className="fa-solid fa-circle-dot"></i>
export const yt = <i className="fa-solid fa-youtube"></i>
export const pencil = <i className="fa-solid fa-pencil"></i>